/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/robot.glb -o src/components/robot/robot.js 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('models/robot.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="sphere_body" geometry={nodes.sphere_body.geometry} material={materials.sphere_color} />
      </group>
    </group>
  )
}

useGLTF.preload('models/robot.glb')
